/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#54647a",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#f39461",
        "success-emerald": "#059669",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed": "#341100",
        "text-main": "#0F172A",
        "on-primary-fixed": "#00164e",
        "outline": "#757682",
        "tertiary-container": "#6e2c00",
        "secondary": "#505f76",
        "on-secondary": "#ffffff",
        "tertiary": "#4b1c00",
        "on-primary-container": "#90a8ff",
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#b6c4ff",
        "warning-amber": "#D97706",
        "error": "#ba1a1a",
        "text-muted": "#475569",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#0b1c30",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "primary-fixed": "#dce1ff",
        "on-primary-fixed-variant": "#264191",
        "primary-container": "#1e3a8a",
        "on-primary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "tertiary-fixed": "#ffdbcb",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444651",
        "surface-tint": "#4059aa",
        "error-container": "#ffdad6",
        "outline-variant": "#c5c5d3",
        "surface-border": "#E2E8F0",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "error-rose": "#E11D48",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#773205",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-primary": "#b6c4ff",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "primary": "#00236f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "32px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "gutter": "24px",
        "base": "4px",
        "container-padding-mobile": "16px",
        "stack-md": "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      boxShadow: {
        "ai-glow": "0 0 20px rgba(144, 168, 255, 0.15)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.4s ease-out forwards",
      },
    },
  },
  plugins: [],
}
